apiVersion: apps/v1
kind: Deployment
metadata:
  name: tunnelgpt
  labels:
    {{- include "tunnelgpt.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "tunnelgpt.selectorLabels" . | nindent 6 }}
      component: tunnelgpt
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        {{- include "tunnelgpt.labels" . | nindent 8 }}
        component: tunnelgpt
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: tunnelgpt
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: tunnelgpt-secrets
                  key: OPENAI_API_KEY
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: tunnelgpt-secrets
                  key: TELEGRAM_BOT_TOKEN
            - name: TELEGRAM_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: tunnelgpt-secrets
                  key: TELEGRAM_WEBHOOK_SECRET
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | quote }}
              memory: {{ .Values.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.resources.limits.cpu | quote }}
              memory: {{ .Values.resources.limits.memory | quote }}
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 5
