apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: tunnelgpt-strip-prefix
spec:
  stripPrefix:
    prefixes:
      - {{ default (printf "/%s" .Release.Namespace) .Values.ingressPath }}
