apiVersion: v1
kind: Service
metadata:
  name: tunnelgpt
  labels:
    {{- include "tunnelgpt.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "tunnelgpt.selectorLabels" . | nindent 4 }}
    component: tunnelgpt
  ports:
    - name: http
      port: 80
      targetPort: 80
